server:
  port: 8041
spring:
  application:
    name: microservice-sidecar-node-service
eureka:
  client:
    service-url:
      defaultZone: http://alex:aabbcc@localhost:8021/eureka/
  instance:
    prefer-ip-address: true
logging:
  config: classpath:logback.xml
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json