server:
  port: 8011
spring:
  application:
    name: microservice-comsumer-movie-unstanding-metadata
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  client:
    service-url:
      defaultZone: http://alex:aabbcc@localhost:8021/eureka/
  instance:
    prefer-ip-address: true
logging:
  config: classpath:logback.xml