server:
  port: 8014
spring:
  application:
    name: microservice-consumer-movie-feign
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  sleuth:
    enabled: true
    log:
      slf4j:
        enabled: true
    feign:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://alex:aabbcc@localhost:8021/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG